//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_BANTINCUAHANG
    {
        public string MABANTIN { get; set; }
        public string MACUAHANG { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNGTOMTAT { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYDANG { get; set; }
        public string HINHANHBANTIN { get; set; }
    
        public virtual SF_CUAHANG SF_CUAHANG { get; set; }
    }
}
