//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_CHITIETHINHANHSANPHAM
    {
        public string MASANPHAM { get; set; }
        public string MAHINHANH { get; set; }
        public Nullable<byte> THUTUSAPXEP { get; set; }
    
        public virtual SF_HINHANHSANPHAM SF_HINHANHSANPHAM { get; set; }
        public virtual SF_SANPHAM SF_SANPHAM { get; set; }
    }
}
