//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_HINHANHSANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_HINHANHSANPHAM()
        {
            this.SF_CHITIETHINHANHSANPHAM = new HashSet<SF_CHITIETHINHANHSANPHAM>();
        }
    
        public string MAHINHANH { get; set; }
        public string TENHINHANH { get; set; }
        public System.DateTime NGAYTAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETHINHANHSANPHAM> SF_CHITIETHINHANHSANPHAM { get; set; }
    }
}
