//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_KHOANGCACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_KHOANGCACH()
        {
            this.SF_CHITIETVANCHUYEN = new HashSet<SF_CHITIETVANCHUYEN>();
        }
    
        public string MATHANHPHODI { get; set; }
        public string MATHANHPHODEN { get; set; }
        public int DODAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETVANCHUYEN> SF_CHITIETVANCHUYEN { get; set; }
        public virtual SF_THANHPHO SF_THANHPHO { get; set; }
        public virtual SF_THANHPHO SF_THANHPHO1 { get; set; }
    }
}
