//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_SANPHAM()
        {
            this.SF_BINHLUAN = new HashSet<SF_BINHLUAN>();
            this.SF_CHITIETGIAMGIA = new HashSet<SF_CHITIETGIAMGIA>();
            this.SF_CHITIETTHUOCTINHSANPHAM = new HashSet<SF_CHITIETTHUOCTINHSANPHAM>();
            this.SF_CHITIETHINHANHSANPHAM = new HashSet<SF_CHITIETHINHANHSANPHAM>();
            this.SF_CHITIETHOADON = new HashSet<SF_CHITIETHOADON>();
            this.SF_DANHGIASANPHAM = new HashSet<SF_DANHGIASANPHAM>();
        }
    
        public string MASANPHAM { get; set; }
        public string MACHUYENMUC { get; set; }
        public string MADONVITINH { get; set; }
        public string MACUAHANG { get; set; }
        public string TENSANPHAM { get; set; }
        public decimal DONGIACU { get; set; }
        public Nullable<decimal> DONGIAMOI { get; set; }
        public Nullable<int> LUOTXEM { get; set; }
        public Nullable<byte> TINHTRANG { get; set; }
        public string MOTA { get; set; }
        public Nullable<byte> LUUNHAP { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public int SOLUONGTONKHO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_BINHLUAN> SF_BINHLUAN { get; set; }
        public virtual SF_CUAHANG SF_CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETGIAMGIA> SF_CHITIETGIAMGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETTHUOCTINHSANPHAM> SF_CHITIETTHUOCTINHSANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETHINHANHSANPHAM> SF_CHITIETHINHANHSANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETHOADON> SF_CHITIETHOADON { get; set; }
        public virtual SF_CHUYENMUC SF_CHUYENMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_DANHGIASANPHAM> SF_DANHGIASANPHAM { get; set; }
        public virtual SF_DONVITINH SF_DONVITINH { get; set; }
    }
}
