//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_THANHPHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_THANHPHO()
        {
            this.SF_KHOANGCACH = new HashSet<SF_KHOANGCACH>();
            this.SF_KHOANGCACH1 = new HashSet<SF_KHOANGCACH>();
            this.SF_QUANHUYEN = new HashSet<SF_QUANHUYEN>();
        }
    
        public string MATHANHPHO { get; set; }
        public string TENTHANHPHO { get; set; }
        public string TENVIETTAT { get; set; }
        public string MABUUCHINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_KHOANGCACH> SF_KHOANGCACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_KHOANGCACH> SF_KHOANGCACH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_QUANHUYEN> SF_QUANHUYEN { get; set; }
    }
}
