//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_BINHLUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_BINHLUAN()
        {
            this.SF_BINHLUAN1 = new HashSet<SF_BINHLUAN>();
        }
    
        public string MABINHLUAN { get; set; }
        public string MABINHLUANCHA { get; set; }
        public string MASANPHAM { get; set; }
        public string MAKHACHHANG { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYBINHLUAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_BINHLUAN> SF_BINHLUAN1 { get; set; }
        public virtual SF_BINHLUAN SF_BINHLUAN2 { get; set; }
        public virtual SF_KHACHHANG SF_KHACHHANG { get; set; }
        public virtual SF_SANPHAM SF_SANPHAM { get; set; }
    }
}
