//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_CHUYENMUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_CHUYENMUC()
        {
            this.SF_CHUYENMUC1 = new HashSet<SF_CHUYENMUC>();
            this.SF_SANPHAM = new HashSet<SF_SANPHAM>();
        }
    
        public string MACHUYENMUC { get; set; }
        public string MACHUYENMUCCHA { get; set; }
        public string TENCHUYENMUC { get; set; }
        public string MOTA { get; set; }
        public string HINHANH { get; set; }
        public int THUTU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHUYENMUC> SF_CHUYENMUC1 { get; set; }
        public virtual SF_CHUYENMUC SF_CHUYENMUC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_SANPHAM> SF_SANPHAM { get; set; }
    }
}
