//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_CUAHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_CUAHANG()
        {
            this.SF_BANTINCUAHANG = new HashSet<SF_BANTINCUAHANG>();
            this.SF_CUAHANGYEUTHICH = new HashSet<SF_CUAHANGYEUTHICH>();
            this.SF_CHUONGTRINHGIAMGIA = new HashSet<SF_CHUONGTRINHGIAMGIA>();
            this.SF_HOADON = new HashSet<SF_HOADON>();
            this.SF_SANPHAM = new HashSet<SF_SANPHAM>();
        }
    
        public string MACUAHANG { get; set; }
        public string MAQUANHUYEN { get; set; }
        public int MAQUYEN { get; set; }
        public string HINHLOGO { get; set; }
        public string TENCUAHANG { get; set; }
        public string HOTENCHUCUAHANG { get; set; }
        public string KHAUHIEU { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAICHINH { get; set; }
        public string DIENTHOAIPHU { get; set; }
        public string MOTA { get; set; }
        public Nullable<byte> CHUNGNHAN { get; set; }
        public string TAIKHOANCUAHANG { get; set; }
        public string MATKHAUCUAHANG { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public byte TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_BANTINCUAHANG> SF_BANTINCUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CUAHANGYEUTHICH> SF_CUAHANGYEUTHICH { get; set; }
        public virtual SF_QUANHUYEN SF_QUANHUYEN { get; set; }
        public virtual SF_NHOMQUYEN SF_NHOMQUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHUONGTRINHGIAMGIA> SF_CHUONGTRINHGIAMGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_HOADON> SF_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_SANPHAM> SF_SANPHAM { get; set; }
    }
}
