//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_GIATRITHUOCTINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_GIATRITHUOCTINH()
        {
            this.SF_CHITIETTHUOCTINHSANPHAM = new HashSet<SF_CHITIETTHUOCTINHSANPHAM>();
        }
    
        public string MAGIATRITHUOCTINH { get; set; }
        public string MATHUOCTINH { get; set; }
        public string TENGIATRITHUOCTINH { get; set; }
        public string MOTA { get; set; }
        public string ICON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETTHUOCTINHSANPHAM> SF_CHITIETTHUOCTINHSANPHAM { get; set; }
        public virtual SF_THUOCTINH SF_THUOCTINH { get; set; }
    }
}
