//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_HOADON()
        {
            this.SF_CHITIETVANCHUYEN = new HashSet<SF_CHITIETVANCHUYEN>();
            this.SF_CHITIETHOADON = new HashSet<SF_CHITIETHOADON>();
        }
    
        public string SOHOADON { get; set; }
        public string MACUAHANG { get; set; }
        public string MAKHACHHANG { get; set; }
        public string MACHUONGTRINHGIAMGIA { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public byte TRANGTHAIHOADON { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual SF_CUAHANG SF_CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETVANCHUYEN> SF_CHITIETVANCHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CHITIETHOADON> SF_CHITIETHOADON { get; set; }
        public virtual SF_CHUONGTRINHGIAMGIA SF_CHUONGTRINHGIAMGIA { get; set; }
        public virtual SF_KHACHHANG SF_KHACHHANG { get; set; }
    }
}
