//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_KHACHHANG()
        {
            this.SF_BINHLUAN = new HashSet<SF_BINHLUAN>();
            this.SF_CUAHANGYEUTHICH = new HashSet<SF_CUAHANGYEUTHICH>();
            this.SF_DANHGIASANPHAM = new HashSet<SF_DANHGIASANPHAM>();
            this.SF_HOADON = new HashSet<SF_HOADON>();
        }
    
        public string MAKHACHHANG { get; set; }
        public string MATKHAU { get; set; }
        public int MAQUYEN { get; set; }
        public string HOTENLOT { get; set; }
        public string TEN { get; set; }
        public Nullable<byte> GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public Nullable<byte> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_BINHLUAN> SF_BINHLUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CUAHANGYEUTHICH> SF_CUAHANGYEUTHICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_DANHGIASANPHAM> SF_DANHGIASANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_HOADON> SF_HOADON { get; set; }
        public virtual SF_NHOMQUYEN SF_NHOMQUYEN { get; set; }
    }
}
