//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_QUANHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SF_QUANHUYEN()
        {
            this.SF_CUAHANG = new HashSet<SF_CUAHANG>();
        }
    
        public string MAQUANHUYEN { get; set; }
        public string MATHANHPHO { get; set; }
        public string TENQUANHUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SF_CUAHANG> SF_CUAHANG { get; set; }
        public virtual SF_THANHPHO SF_THANHPHO { get; set; }
    }
}
